version: '3'

services:
  app:
    build: .
    environment:
      - NODE_ENV=production
      - REDIS_HOST=redis
      - MONGO_HOST=mongodb
    ports:
      - "3000:3000"
    depends_on:
      - redis
      # - mongodb

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  # mongodb:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"